// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlk_G5xDxRJaja50XSdjZjPfdE0z4K1J0',
    appId: '1:835271127477:web:7d2563fd92471fa168e9fc',
    messagingSenderId: '835271127477',
    projectId: 'unsaid-46587',
    authDomain: 'unsaid-46587.firebaseapp.com',
    storageBucket: 'unsaid-46587.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlk_G5xDxRJaja50XSdjZjPfdE0z4K1J0',
    appId: '1:835271127477:android:7d2563fd92471fa168e9fc',
    messagingSenderId: '835271127477',
    projectId: 'unsaid-46587',
    storageBucket: 'unsaid-46587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlk_G5xDxRJaja50XSdjZjPfdE0z4K1J0',
    appId: '1:835271127477:ios:2e117f674ed52e7168e9fc',
    messagingSenderId: '835271127477',
    projectId: 'unsaid-46587',
    storageBucket: 'unsaid-46587.appspot.com',
    iosBundleId: 'com.example.unsaid',
    iosClientId:
        '835271127477-u0h6d56vcdrn9o650palli5bh3kg69n9.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlk_G5xDxRJaja50XSdjZjPfdE0z4K1J0',
    appId: '1:835271127477:ios:2e117f674ed52e7168e9fc',
    messagingSenderId: '835271127477',
    projectId: 'unsaid-46587',
    storageBucket: 'unsaid-46587.appspot.com',
    iosBundleId: 'com.example.unsaid',
    iosClientId:
        '835271127477-u0h6d56vcdrn9o650palli5bh3kg69n9.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlk_G5xDxRJaja50XSdjZjPfdE0z4K1J0',
    appId: '1:835271127477:web:7d2563fd92471fa168e9fc',
    messagingSenderId: '835271127477',
    projectId: 'unsaid-46587',
    authDomain: 'unsaid-46587.firebaseapp.com',
    storageBucket: 'unsaid-46587.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
