name: Deploy Inference Service

on:
  push:
    branches: [ main ]
    paths:
      - 'services/inference/**'
      - '.github/workflows/deploy-inference.yml'
  workflow_dispatch:

env:
  SERVICE_NAME: unsaid-inference
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        cd services/inference
        gcloud builds submit --tag ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/inference/${{ env.SERVICE_NAME }}:latest .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/inference/${{ env.SERVICE_NAME }}:latest \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8080 \
          --memory 2Gi \
          --cpu 1 \
          --max-instances 10 \
          --concurrency 80 \
          --timeout 300 \
          --set-env-vars INF_TOKEN=${{ secrets.INF_TOKEN }}

    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)')
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
        echo "🚀 Inference service deployed to: $SERVICE_URL"

    - name: Update Vercel environment
      if: success()
      run: |
        if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "Updating Vercel INF_BASE_URL to: ${{ env.SERVICE_URL }}"
          # This would require Vercel CLI or API call to update env vars
          # For now, just log the URL for manual update
        fi