name: Deploy Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/deploy-vercel.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - name: Pull Vercel env
        run: npx vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
      - name: Build
        run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy
        run: npx vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}